AcademiaBaile/AcademiaBaile/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from Academia import views as academia_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', academia_views.index_view, name='index'),
    url(r'^login', academia_views.login_view, name = 'login'),
    url(r'^home/', academia_views.home_view, name='home'),
    url(r'^logout', academia_views.login_out, name = 'logout'),
    url(r'^lista_alumnos/', academia_views.lista_alumnos, name='lista_alumnos'),
    url(r'^lista_clases/', academia_views.lista_clases, name='lista_clases'),
    url(r'^agregar_alumno/', academia_views.agregar_alumno, name='agregar_alumno'),
    url(r'^agregar_clase/', academia_views.agregar_clase, name='agregar_clase'),
    url(r'^eliminar_clase/(?P<id_clase>[-A-Za-z0-9_]+)$', academia_views.eliminar_clase, name='eliminar_clase'),
    url(r'^eliminar_alumno/(?P<id_alumno>[-A-Za-z0-9_]+)$', academia_views.eliminar_alumno, name='eliminar_alumno'),
    url(r'^modificar_alumno/(?P<id_alumno>[-A-Za-z0-9_]+)$', academia_views.modificar_alumno, name='modificar_alumno'),
    url(r'^modificar_clase/(?P<id_clase>[-A-Za-z0-9_]+)$', academia_views.modificar_clase, name='modificar_clase'),
    url(r'^eventos/', academia_views.eventos, name='eventos'),
    url(r'^maestros/', academia_views.maestros, name='maestros'),
    url(r'^contacto/', academia_views.contacto, name='contacto'),
    url(r'^lista_alumnos_clase/(?P<id_clase>[-A-Za-z0-9_]+)$', academia_views.lista_alumnos_clase, name='lista_alumnos_clase'),
    url(r'^singlep/', academia_views.singlep, name='singlep'),
    url(r'^singlep2/', academia_views.singlep2, name='singlep2'),
    url(r'^singlep3/', academia_views.singlep3, name='singlep3'),
    url(r'^singlep4/', academia_views.singlep4, name='singlep4'),
]

AcademiaBaile/Academia/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Usuario(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	usuario = models.CharField(max_length=600, blank=True, null=True, unique=True)
	correo = models.CharField(max_length=600, blank=True, null=True, unique=True)
	contraseña = models.CharField(max_length=6000, blank=True, null=True)

	def __str__(self):
		return str ("Usuario: "+(self.usuario))

class Clase(models.Model):
	nombre = models.CharField(max_length=600)
	horario = models.CharField(max_length=6000, blank=True, null=True)

	def __str__(self):
		return str ("Clase: "+(self.nombre)+" "+(self.horario))

class Alumno(models.Model):
	nombre = models.CharField(max_length=600)
	a_paterno = models.CharField(max_length=600)
	a_materno = models.CharField(max_length=600, blank=True, null=True)
	#correo = models.CharField(max_length=600, blank=True, null=True, unique=True)
	edad = models.IntegerField(default=1, blank=True, null=True)
	clase = models.ForeignKey(Clase, on_delete=models.CASCADE, related_name="alumno_clase", blank=False, null=False)

	def __str__(self):
		return str ("Alumno: "+(self.nombre)+" "+(self.a_paterno)+" "+str(self.clase))

AcademiaBaile/Academia/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from Academia.models import *
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def index_view(request, template_name = 'Academia/index.html'):
    '''
    Función home

    Es la primera vista despues de que el usuario se logueo

    Parametros:
        -request            --[peticion]--      nos permite obtener el usuario logueado 
        -template_name      --[string]--        proporciona la url vinculada a la función
    Excepciones:
        -sin excepciones    --
    Return:
        -locals()           --[encapsulado]--   retorna todas las variables declaradas en el views
    '''
    '''try:
        usuario = request.user
        user =  User.objects.get(username = usuario)
        usuarioExt = Usuario.objects.get(user = user)
        isAdministrador = user.groups.filter(name = 'Administrador').exists()
    except:
        return HttpResponseRedirect('/login/')
    estado = 0#Bandera de alertas
    mensaje = ""#Mensaje de la alerta
    count_instrumentos = Instrumento.objects.filter(usuario=usuarioExt).count()
    count_grupos = Cat_grupo.objects.filter(usuario=usuarioExt).count()'''
    return render(request, template_name, locals(),)


def login_view(request, template_name = 'Academia/login.html'):
    #Modulo que permite a los usuarios ingresar sus datos de usuario y contraseña para acceder a las distintas funciones del sistema
    #Declaramos las variables iniciales para el manejo de la informacion del formulario
    state = ""
    username = ""
    password = ""
    next = ""
    estado = 0#Bandera de alertas
    mensaje = ""#Mensaje de alerta
    if request.GET:
        next = request.GET['next']
    #Si el formulario es mandado por metodo post
    if request.POST:
        #Obtenemso los datos del formulario
        username = request.POST['username']
        password = request.POST['password']
        try:
            if '@' in username:
                check = User.objects.get(email=username)
            else:
                check = User.objects.get(username=username)
            username = check.username
            #Col dos datos del formulario validamos que estos pertenezcan a algun usuario den la base de datos
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if next == "":
                        request.session.set_expiry(14400)#4 horas para que caduque la session
                        #check.last_login = datetime.now()
                        #check.save()
                        return HttpResponseRedirect('/home/')
                    else:
                        return HttpResponseRedirect(next)
                else:
                    #Mandamos la excepcion en caso de que un usuario aun sin activar trate de ingresar
                    estado = 1
                    mensaje = "¡Lo sentimos! Este usuario debe activarse."
                    #messages.warning(request, mensaje)
                    return render(request, template_name, locals(),)
            valid = check.check_password(password)
            if not valid:
                #Si la contraseña no es valida
                estado = 1
                mensaje = "¡Hay un problema! La contraseña es incorrecta."
                #messages.warning(request, mensaje)
                return render(request, template_name, locals(),)
        except ObjectDoesNotExist:
            if '@' in username:
                #Si el usuario no esta registrado en la base de datos
                estado = 1
                mensaje = "¡Lo sentimos! El email no existe, registrese por favor."
                #messages.info(request, mensaje)
                return render(request, template_name, locals(),)
            else:
                estado = 1
                mensaje = "¡Upps! El nombre de usuario no existe, registrese por favor."
                ##messages.warning(request, mensaje)
                return render(request, template_name, locals(),)

    return render(request, template_name, {'mensaje':mensaje, 'username': username, 'next': next,},)


def home_view(request, template_name = 'Academia/home.html'):
    '''
    Función home

    Es la primera vista despues de que el usuario se logueo

    Parametros:
        -request            --[peticion]--      nos permite obtener el usuario logueado 
        -template_name      --[string]--        proporciona la url vinculada a la función
    Excepciones:
        -sin excepciones    --
    Return:
        -locals()           --[encapsulado]--   retorna todas las variables declaradas en el views
    '''
    try:
        usuario = request.user
        user =  User.objects.get(username = usuario)
        usuarioExt = Usuario.objects.get(user = user)
        isAdministrador = user.groups.filter(name = 'Administrador').exists()
    except:
        return HttpResponseRedirect('/login')
    estado = 0#Bandera de alertas
    mensaje = ""#Mensaje de la alerta
    #count_instrumentos = Instrumento.objects.filter(usuario=usuarioExt).count()
    #xcount_grupos = Cat_grupo.objects.filter(usuario=usuarioExt).count()
    return render(request, template_name, locals(),)


def login_out(request):
    #Pagina a la que se accede despues de un logout del usuario
    logout(request)
    return HttpResponseRedirect('/')


def lista_alumnos(request, template_name = 'Academia/lista_alumnos.html'):
    '''
    Función home

    Es la primera vista despues de que el usuario se logueo

    Parametros:
        -request            --[peticion]--      nos permite obtener el usuario logueado 
        -template_name      --[string]--        proporciona la url vinculada a la función
    Excepciones:
        -sin excepciones    --
    Return:
        -locals()           --[encapsulado]--   retorna todas las variables declaradas en el views
    '''
    try:
        usuario = request.user
        user =  User.objects.get(username = usuario)
        usuarioExt = Usuario.objects.get(user = user)
        isAdministrador = user.groups.filter(name = 'Administrador').exists()
    except:
        return HttpResponseRedirect('/login')
    estado = 0#Bandera de alertas
    mensaje = ""#Mensaje de la alerta
    #count_instrumentos = Instrumento.objects.filter(usuario=usuarioExt).count()
    #xcount_grupos = Cat_grupo.objects.filter(usuario=usuarioExt).count()
    alumnos = Alumno.objects.all()
    return render(request, template_name, locals(),)


def lista_clases(request, template_name = 'Academia/lista_clases.html'):
    '''
    Función home

    Es la primera vista despues de que el usuario se logueo

    Parametros:
        -request            --[peticion]--      nos permite obtener el usuario logueado 
        -template_name      --[string]--        proporciona la url vinculada a la función
    Excepciones:
        -sin excepciones    --
    Return:
        -locals()           --[encapsulado]--   retorna todas las variables declaradas en el views
    '''
    try:
        usuario = request.user
        user =  User.objects.get(username = usuario)
        usuarioExt = Usuario.objects.get(user = user)
        isAdministrador = user.groups.filter(name = 'Administrador').exists()
    except:
        return HttpResponseRedirect('/login')
    estado = 0#Bandera de alertas
    mensaje = ""#Mensaje de la alerta
    #count_instrumentos = Instrumento.objects.filter(usuario=usuarioExt).count()
    #xcount_grupos = Cat_grupo.objects.filter(usuario=usuarioExt).count()
    clases = Clase.objects.all()
    if request.method == "POST":
        nombre = request.POST['nombre']
        if Clase.objects.all().filter(nombre__icontains=nombre).exists():
            clases = Clase.objects.all().filter(nombre__icontains=nombre)
            return render(request, template_name, locals(),)
        else:
            estado = 1
            mensaje = 'No se encontraron coincidencias en la busqueda!'
            return render(request, template_name, locals(),)
    return render(request, template_name, locals(),)


def agregar_alumno(request, template_name = 'Academia/agregar_alumno.html'):
    '''
    Función home

    Es la primera vista despues de que el usuario se logueo

    Parametros:
        -request            --[peticion]--      nos permite obtener el usuario logueado 
        -template_name      --[string]--        proporciona la url vinculada a la función
    Excepciones:
        -sin excepciones    --
    Return:
        -locals()           --[encapsulado]--   retorna todas las variables declaradas en el views
    '''
    try:
        usuario = request.user
        user =  User.objects.get(username = usuario)
        usuarioExt = Usuario.objects.get(user = user)
        isAdministrador = user.groups.filter(name = 'Administrador').exists()
    except:
        return HttpResponseRedirect('/login')
    estado = 0#Bandera de alertas
    mensaje = ""#Mensaje de la alerta
    #count_instrumentos = Instrumento.objects.filter(usuario=usuarioExt).count()
    #xcount_grupos = Cat_grupo.objects.filter(usuario=usuarioExt).count()
    clases = Clase.objects.all()
    if request.method == "POST":
        nombre = request.POST['nombre']
        a_paterno = request.POST['a_paterno']
        a_materno = request.POST['a_materno']
        edad = request.POST['edad']
        clase = request.POST['clase']
        if Alumno.objects.all().filter(nombre=nombre, a_paterno=a_paterno, a_materno=a_materno, edad=edad).exists():
            estado = 1
            mensaje = 'Ya existe el alumno!'
            return render(request, template_name, locals(),)
        else:
            clase_obj = Clase.objects.get(pk=clase)

AcademiaBaile/templates/Academia/agregar_alumno.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <link rel="shortcut icon" href="#" />
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Nuevo Alumno</title>

        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/sweetalert2/sweetalert2.min.css' %}">        
        
        <link rel="stylesheet" type="text/css" href="{% static 'fuentes/iconic/css/material-design-iconic-font.min.css' %}">
        <script type="text/javascript">
            function mensajes(estado,mensaje)
            {
                if (estado != 0) 
                {
                    alert(mensaje);
                }
            }
        </script>

        <link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
        <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <!--<script src="js/jquery.easydropdown.js"></script>-->
        <!--start slider -->
        <link rel="stylesheet" href="{% static 'css/fwslider.css' %}" media="all">
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/fwslider.js' %}"></script>

        <script type="text/javascript">
            $(document).ready(function() {
                $(".dropdown img.flag").addClass("flagvisibility");

                $(".dropdown dt a").click(function() {
                    $(".dropdown dd ul").toggle();
                });
                            
                $(".dropdown dd ul li a").click(function() {
                    var text = $(this).html();
                    $(".dropdown dt a span").html(text);
                    $(".dropdown dd ul").hide();
                    $("#result").html("Selected value is: " + getSelectedValue("sample"));
                });
                            
                function getSelectedValue(id) {
                    return $("#" + id).find("dt a span.value").html();
                }

                $(document).bind('click', function(e) {
                    var $clicked = $(e.target);
                    if (! $clicked.parents().hasClass("dropdown"))
                        $(".dropdown dd ul").hide();
                });


                $("#flagSwitcher").click(function() {
                    $(".dropdown img.flag").toggleClass("flagvisibility");
                });
            });
         </script>
        
    </head>
    
    <body onload="mensajes('{{estado}}','{{mensaje}}');">

        <div class="header">
        <div class="container">
            <div class="row">
              <div class="col-md-12">
                 <div class="header-left">
                     <div class="logo">
                        <a href="/admin"><img src="{% static 'images/logo.jpg' %}" alt=""/></a>
                     </div>
                     <div class="menu">
                          <a class="toggleMenu" href="#"><img src="{% static 'images/nav.png' %}" alt="" /></a>
                            <ul class="nav" id="nav">
                                <li><a href="{% url 'lista_alumnos' %}">Alumnos</a></li>
                                <li><a href="{% url 'lista_clases' %}">Clases</a></li>                          
                                <div class="clear"></div>
                            </ul>
                            <script type="text/javascript" src="{% static 'js/responsive-nav.js' %}"></script>
                    </div>                          
                    <div class="clear"></div>
                </div>
                <div class="header_right">
                        <!----search-scripts---->
                        <script src="{% static 'js/classie.js' %}"></script>
                        <script src="{% static 'js/uisearch.js' %}"></script>
                        <script>
                            new UISearch( document.getElementById( 'sb-search' ) );
                        </script>
                        <!----//search-scripts---->
                    <ul class="icon1 sub-icon1 profile_img">
                     <li class="login_button"><a href="{% url 'logout' %}">Logout</a></li>
                   </ul>
                   <div class="clear"></div>
                </div>
              </div>
         </div>
        </div>
    </div>

     
      <div class="container-login">
        <div class="wrap-login">
            <form class="login-form validate-form" id="formLogin" action="" method="post">
            	{% csrf_token %}
                <span class="login-form-title">Nuevo Alumno</span>
                
                <div class="wrap-input100">
                    <input class="input100" type="text" id="id_nombre" name="nombre" placeholder="Nombre" required="true">
                    <span class="focus-efecto"></span>
                </div>

                <div class="wrap-input100">
                    <input class="input100" type="text" id="id_a_paterno" name="a_paterno" placeholder="Apellido Paterno" required="true">
                    <span class="focus-efecto"></span>
                </div>

                <div class="wrap-input100">
                    <input class="input100" type="text" id="id_a_materno" name="a_materno" placeholder="Apellido Materno">
                    <span class="focus-efecto"></span>
                </div>

                <div class="wrap-input100">
                    <input class="input100" type="number" id="id_edad" name="edad" placeholder="Edad" min='1' required="true">
                    <span class="focus-efecto"></span>
                </div>
                
                <div class="wrap-input100">
                    <select id="id_clase" name="clase" title="Elija una asignatura" required="">
                        <option value="" disabled="" selected="">Seleccione una clase</option>
                        {% for asignatura in clases %}
                            <option value="{{asignatura.pk}}">{{ asignatura.nombre }} : {{asignatura.horario}}</option>
                        {% endfor %}

                        <!--<option value="Seccion">Grupo 1</option>
                        <option value="Seccion">Grupo 2</option>
                        <option value="Seccion">Grupo 3</option>
                        <option value="Seccion">Grupo 4</option>-->
                    </select>
                    <span class="focus-efecto"></span>
                </div>
                
                <div class="container-login-form-btn">
                    <div class="wrap-login-form-btn">
                        <div class="login-form-bgbtn"></div>
                        <button type="submit" name="submit" class="login-form-btn">Agregar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>     
        
        
     <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>    
     <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>    
     <script src="{% static 'popper/popper.min.js' %}"></script>    
        
     <script src="{% static 'plugins/sweetalert2/sweetalert2.all.min.js' %}"></script>    
     <!--<script src="{% static 'codigo.js' %}"></script>-->
    </body>
</html>

AcademiaBaile/templates/Academia/agregar_clase.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <link rel="shortcut icon" href="#" />
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Nueva Clase</title>

        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/sweetalert2/sweetalert2.min.css' %}">        
        
        <link rel="stylesheet" type="text/css" href="{% static 'fuentes/iconic/css/material-design-iconic-font.min.css' %}">
        <script type="text/javascript">
            function mensajes(estado,mensaje)
            {
                if (estado != 0) 
                {
                    alert(mensaje);
                }
            }
        </script>

        <link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
        <link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <!--<script src="js/jquery.easydropdown.js"></script>-->
        <!--start slider -->
        <link rel="stylesheet" href="{% static 'css/fwslider.css' %}" media="all">
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/fwslider.js' %}"></script>

        <script type="text/javascript">
            $(document).ready(function() {
                $(".dropdown img.flag").addClass("flagvisibility");

                $(".dropdown dt a").click(function() {
                    $(".dropdown dd ul").toggle();
                });
                            
                $(".dropdown dd ul li a").click(function() {
                    var text = $(this).html();
                    $(".dropdown dt a span").html(text);
                    $(".dropdown dd ul").hide();
                    $("#result").html("Selected value is: " + getSelectedValue("sample"));
                });
                            
                function getSelectedValue(id) {
                    return $("#" + id).find("dt a span.value").html();
                }

                $(document).bind('click', function(e) {
                    var $clicked = $(e.target);
                    if (! $clicked.parents().hasClass("dropdown"))
                        $(".dropdown dd ul").hide();
                });


                $("#flagSwitcher").click(function() {
                    $(".dropdown img.flag").toggleClass("flagvisibility");
                });
            });
         </script>
        
    </head>
    
    <body onload="mensajes('{{estado}}','{{mensaje}}');">

        <div class="header">
        <div class="container">
            <div class="row">
              <div class="col-md-12">
                 <div class="header-left">
                     <div class="logo">
                        <a href="/admin"><img src="{% static 'images/logo.jpg' %}" alt=""/></a>
                     </div>
                     <div class="menu">
                          <a class="toggleMenu" href="#"><img src="{% static 'images/nav.png' %}" alt="" /></a>
                            <ul class="nav" id="nav">
                                <li><a href="{% url 'lista_alumnos' %}">Alumnos</a></li>
                                <li><a href="{% url 'lista_clases' %}">Clases</a></li>                          
                                <div class="clear"></div>
                            </ul>
                            <script type="text/javascript" src="{% static 'js/responsive-nav.js' %}"></script>
                    </div>                          
                    <div class="clear"></div>
                </div>
                <div class="header_right">
                        <!----search-scripts---->
                        <script src="{% static 'js/classie.js' %}"></script>
                        <script src="{% static 'js/uisearch.js' %}"></script>
                        <script>
                            new UISearch( document.getElementById( 'sb-search' ) );
                        </script>
                        <!----//search-scripts---->
                    <ul class="icon1 sub-icon1 profile_img">
                     <li class="login_button"><a href="{% url 'logout' %}">Logout</a></li>
                   </ul>
                   <div class="clear"></div>
                </div>
              </div>
         </div>
        </div>
    </div>

     
      <div class="container-login">
        <div class="wrap-login">
            <form class="login-form validate-form" id="formLogin" action="" method="post">
            	{% csrf_token %}
                <span class="login-form-title">Nueva Clase</span>
                
                <div class="wrap-input100">
                    <input class="input100" type="text" id="id_nombre" name="nombre" placeholder="Nombre" required="true">
                    <span class="focus-efecto"></span>
                </div>

                <div class="wrap-input100">
                    <input class="input100" type="text" id="id_horario" name="horario" placeholder="Horario" required="true">
                    <span class="focus-efecto"></span>
                </div>
                
                <div class="container-login-form-btn">
                    <div class="wrap-login-form-btn">
                        <div class="login-form-bgbtn"></div>
                        <button type="submit" name="submit" class="login-form-btn">Agregar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>     
        
        
     <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>    
     <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>    
     <script src="{% static 'popper/popper.min.js' %}"></script>    
        
     <script src="{% static 'plugins/sweetalert2/sweetalert2.all.min.js' %}"></script>    
     <!--<script src="{% static 'codigo.js' %}"></script>-->
    </body>
</html>

AcademiaBaile/templates/Academia/login.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <link rel="shortcut icon" href="#" />
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Login</title>

        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/sweetalert2/sweetalert2.min.css' %}">        
        
        <link rel="stylesheet" type="text/css" href="{% static 'fuentes/iconic/css/material-design-iconic-font.min.css' %}">
        
    </head>
    
    <body>
     
      <div class="container-login">
        <div class="wrap-login">
            <form class="login-form validate-form" id="formLogin" action="" method="post">
            	{% csrf_token %}
                <span class="login-form-title">LOGIN</span>
                
                <div class="wrap-input100" data-validate = "Usuario incorrecto">
                    <input class="input100" type="text" id="usuario" name="username" placeholder="Usuario">
                    <span class="focus-efecto"></span>
                </div>
                
                <div class="wrap-input100" data-validate="Password incorrecto">
                    <input class="input100" type="password" id="password" name="password" placeholder="Password">
                    <span class="focus-efecto"></span>
                </div>
                
                <div class="container-login-form-btn">
                    <div class="wrap-login-form-btn">
                        <div class="login-form-bgbtn"></div>
                        <button type="submit" name="submit" class="login-form-btn">CONECTAR</button>
                    </div>
                </div>
            </form>
        </div>
    </div>     
        
        
     <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>    
     <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>    
     <script src="{% static 'popper/popper.min.js' %}"></script>    
        
     <script src="{% static 'plugins/sweetalert2/sweetalert2.all.min.js' %}"></script>    
     <!--<script src="{% static 'codigo.js' %}"></script>-->
    </body>
</html>